### ISSUE TITLE
Animation type change doesn't seem to apply!

### ISSUE THREAD

**Issue by hmaffin** [danielstorey/adapt-expose#4]
I get the same looking transition no matter what I pick.

**Comment by danielstorey** [comment]
What transition are you getting?

**Comment by hmaffin** [comment]
Hard to say but just looks like fade.

All the best,
Helen
==================================
Helen Maffin
e-Learning Developer
hlm56@cam.ac.uk<mailto:hlm56@cam.ac.uk>
---------------------------
University of Cambridge
Finance Division
Greenwich House
Madingley Rise
Madingley Road
Cambridge, CB3 0TX
---------------------------
Tel: 01223 764659
Fax: 01223 765988
==================================

**Comment by danielstorey** [comment]
Sorry, the properties.schema was missing underscores for animationType and columns properties. Please reinstall the plugin and try again. This should sort #5 as well.

**Comment by hmaffin** [comment]
Did you increment the version number? Telling me it already exists.

**Comment by danielstorey** [comment]
Ummm....no but I have now.

**Comment by danielstorey** [comment]
So is it working now?

**Comment by hmaffin** [comment]
Yep!!! Slides down and everything :)

![image](https://cloud.githubusercontent.com/assets/11558341/20760029/a1bdee24-b716-11e6-87ca-b313c29902da.png)
