### ISSUE TITLE
Columns not working

### ISSUE THREAD

**Issue by hmaffin** [danielstorey/adapt-expose#5]
I put 3 for the column width but my 3 items are stacked one on top of the other in full width mode.

![image](https://cloud.githubusercontent.com/assets/11558341/20752039/0b80d148-b6f7-11e6-843a-5b34b9160b30.png)

**Comment by danielstorey** [comment]
Are you using the AT?

**Comment by hmaffin** [comment]
Yep. Latest version of FW and AT.

All the best,
Helen
==================================
Helen Maffin
e-Learning Developer
hlm56@cam.ac.uk<mailto:hlm56@cam.ac.uk>
---------------------------
University of Cambridge
Finance Division
Greenwich House
Madingley Rise
Madingley Road
Cambridge, CB3 0TX
---------------------------
Tel: 01223 764659
Fax: 01223 765988
==================================

**Comment by hmaffin** [comment]
Working!!!
