### ISSUE TITLE
Minimum height

### ISSUE THREAD

**Issue by hmaffin** [danielstorey/adapt-expose#6]
Hi Dan,

Is it possible to have an optional minimum height setting as if you have slightly different amounts of text, they look a bit untidy!

![image](https://cloud.githubusercontent.com/assets/11558341/20799377/e61913e6-b7d9-11e6-9159-39f9b4463a09.png)

**Comment by danielstorey** [comment]
Hi Helen,

Are you comfortable using less? You can give the `.reveal-item-content` class a fixed height. Either way leave this issue open as I think it will be a good idea to match all item heights to the highest one.

**Comment by danielstorey** [comment]
In latest version 1.1.0 heights are automatically set to match tallest item. This behaviour can be overridden - see README

**Comment by hmaffin** [comment]
Working fantastically now!
